### ISSUE TITLE
Blank caption files after running the tagger

### ISSUE THREAD

**Issue by nothelloearth1** [Haoming02/TensorRT-Toolkits#1]
Hello. I have managed to get the tagger up and running, but I keep getting 0 bytes text files, and the caption files are empty.

**Comment by Haoming02** [comment]
Yeah. Somehow I got the same problem on another PC as well...

Try edit the following line to:

```py
model = TrtModel("WD14.trt”)
```

https://github.com/Haoming02/TensorRT-Toolkits/blob/main/tag.py#L50

**Comment by nothelloearth1** [comment]
Can confirm it works now. Thanks for your hard work.
